doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        options:
            1002: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        report_fields_where_declared: true
        mappings:
            SonataUserBundle: ~
            SonataMediaBundle: ~
            SonataPageBundle: ~
#            gedmo_loggable:
#                type: annotation
#                prefix: Gedmo\Mapping\Annotation
#                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Mapping/Annotation"
#                alias: Gedmo
#                is_bundle: false
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

#        mappings:
#            SonataUserBundle: ~
#            SonataMediaBundle: ~
#            SonataPageBundle: ~
#
#            gedmo_loggable: # ou un autre nom de votre choix
#                type: annotation
#                prefix: Gedmo\Mapping\Annotation
#                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Mapping/Annotation"
#                alias: Gedmo
#                is_bundle: false
#            App:
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
#        filters:
#            softdeleteable:
#                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
#                enabled: true

        controller_resolver:
            auto_mapping: true


        resolve_target_entities:
            Partitech\SonataMenu\Model\MenuInterface: App\Entity\Menu
            Partitech\SonataMenu\Model\MenuItemInterface: App\Entity\MenuItem

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
