## Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
#liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"

liip_imagine:
    driver: "imagick"
    twig:
        mode: lazy
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public" # %kernel.project_dir%/public (%kernel.project_dir%/web for Symfony < 4.0.0)
                cache_prefix: 'media/cache' # media/cache
    filter_sets :

        # use the default cache configuration
        cache : ~
        #
        #        # an example thumbnail transformation definition
        #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails

